In [2]:

!pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl 
!pip install torchvision

ERROR: torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.


In [3]:
import torch
#Torch = a tensor library similar to Numpy, with strong gpu support 
#torch.autograd a "tape-based"
#torch.nn = a neural netwok library deeply integrated with autograd
#torch.optim = an opti[InternetShortcut]
URL=http://localhost:8888/notebooks/Untitled18.ipynb?kernel_name=python3#
mization package to be used with torch.. with standard automatization methods such as SGD, RMSProp, LBFGS 

In [6]:
import torch.autograd as autograd 
import torch.nn as nn
import torch.optim as optim 

torch.manual_seed(123)

In [13]:
m_tensor = torch.randn((6,3,28,28))
print(type(m_tensor))
print(m_tensor)

<class 'torch.Tensor'>
tensor([[[[ 2.9714e-01,  4.7929e-01, -9.6952e-01,  ...,  9.0861e-01,
            9.8194e-01,  4.0040e-01],
          [ 2.9578e-01,  1.3425e-01, -8.5632e-02,  ...,  6.5575e-01,
            1.9794e+00, -8.6856e-01],
          [-2.0729e-01, -2.2627e-01, -9.1795e-01,  ..., -1.3047e+00,
           -8.0329e-01,  5.9537e-01],
          ...,
          [ 2.3589e+00, -2.0969e+00,  5.4817e-01,  ...,  9.5239e-01,
            5.3480e-01, -1.1298e+00],
          [-7.1010e-01,  3.5647e-01, -7.6956e-01,  ..., -8.4754e-01,
            1.1492e+00, -2.4837e+00],
          [ 1.1202e-01, -2.5119e+00,  9.9588e-01,  ..., -2.9346e-01,
            1.4595e+00,  2.0902e+00]],

         [[-8.4656e-01, -5.1272e-02,  2.0078e-01,  ..., -3.5535e-03,
            6.3483e-01, -5.0859e-02],
          [ 4.3641e-01, -8.1143e-02,  1.1736e+00,  ..., -6.5597e-01,
            7.9260e-01, -6.6497e-01],
          [-2.6949e+00, -1.1352e+00, -3.1672e-01,  ...,  3.7791e-01,
           -2.1633e+00, -1.1131e-01

In [14]:
m_tensor = torch.randn((5, 4, 4, 4))
m_tensor[0]

tensor([[[ 0.1126, -0.5080,  1.3963, -0.9982],
         [-0.9722, -0.7995,  0.0193,  1.0132],
         [-0.2630,  0.2004, -0.5409,  0.7860],
         [-0.7527, -1.0960, -0.0907,  0.5905]],

        [[-0.5566, -0.0990,  0.3244,  0.2158],
         [ 1.2312, -1.9092,  2.6365,  0.0271],
         [-0.4966,  0.5105,  0.3002, -0.8655],
         [-0.8595,  1.3072, -0.2146,  0.5647]],

        [[-0.5863,  0.5063,  0.2676, -0.3561],
         [ 1.0894, -0.5310,  0.6345,  0.0763],
         [ 2.1373, -1.6327,  0.3530,  0.1181],
         [-0.5277, -1.0087,  1.7996, -0.1836]],

        [[-0.6670,  0.9659,  1.5912,  0.4057],
         [-0.8522, -0.8579, -1.0611,  0.4697],
         [ 1.5058, -0.3957,  0.4437, -0.6925],
         [ 0.0455,  0.9625, -1.7021, -1.7968]]])

In [18]:
x = torch.randn(4, 3)
y = torch.randn(3, 4)


In [20]:
print(x)

tensor([[-1.3247,  0.4204, -1.6691],
        [ 0.0152,  0.8363,  0.8031],
        [ 0.3581,  0.7514, -0.2564],
        [ 1.0914, -0.8307, -1.4775]])


In [21]:
print(y)

tensor([[ 0.4350, -0.7155, -0.4324,  0.6886],
        [-1.0028, -2.3323, -0.5313, -1.1063],
        [-1.0543,  1.2600,  1.2362, -0.8375]])


In [25]:
#create a torch.Tensor object from  python lists 
v = [1,2,3]
print(type(v))
v_tensor = torch.Tensor(v)
print(v_tensor)

<class 'list'>
tensor([1., 2., 3.])


In [28]:
#create a torch.Tensor object of size 2 x 3 from 2 x 3 matrix
m2x3 = [[1,2,3],[ 4,5,6]]
m2x3_tensor = torch.Tensor(m2x3)
print(m2x3_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [30]:
#create a 3d torch.Tensor object of size 3 x 3 x 3
m3x3x3 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
          [[10, 11, 12],[13, 14, 15], [16, 17, 18]],
            [[19, 20, 21],[22, 23, 24], [25, 26, 27]]]
m3x3x3_tensor = torch.Tensor(m3x3x3)
print(m3x3x3_tensor)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])


In [31]:
#Create a 4Dtensor from random data and given dimensions (in this case 3x4x5x6) with torch.randn()
m4x3x3x3_tensor = torch.randn((4, 3, 3, 3))
m4x3x3x3_tensor.shape
print(m4x3x3x3_tensor)

tensor([[[[ 1.3028, -0.8751,  1.3818],
          [ 0.4512,  0.8014, -1.0618],
          [ 0.1059, -0.9035,  1.2245]],

         [[-0.6427,  0.7037,  0.1079],
          [-0.3614,  0.5114,  0.7012],
          [ 0.6542,  2.0290, -1.0596]],

         [[-0.8264, -0.1904,  0.4576],
          [-0.2208, -1.9848,  0.6105],
          [-0.7540,  1.9948, -0.5894]]],


        [[[ 1.7876,  0.8769,  0.8108],
          [ 1.5727,  1.3169, -0.8892],
          [ 1.4896,  0.8101, -1.8400]],

         [[-1.4865, -0.2843,  0.2154],
          [ 0.5087, -0.0204, -1.1449],
          [-0.5770, -1.5423, -0.6685]],

         [[ 1.4206,  2.1888,  0.0440],
          [ 2.3219,  1.5177, -0.3587],
          [ 1.4578,  0.3333,  0.3812]]],


        [[[-0.6118, -1.0119,  1.1069],
          [ 0.0156, -0.2695,  0.3455],
          [ 1.6507, -0.1778,  1.1760]],

         [[ 1.0990,  0.5384,  0.5320],
          [ 0.6659, -0.1833,  0.2670],
          [ 0.6832, -0.7274,  0.8032]],

         [[ 0.8063,  0.3217, -1.4681],
     